spring:
  config:
    activate:
      on-profile: prod

# Configuración estricta para el entorno de Producción
management:
  endpoints:
    web:
      exposure:
        include: health
        # EXCLUSIÓN ESTRICTA: No exponer env, loggers, ni otros datos sensibles en prod
  endpoint:
    health:
      show-details: never # Ocultar detalles del disco y BD al público

springdoc:
  api-docs:
    enabled: false # Desactivar JSON de Swagger en prod
  swagger-ui:
    enabled: false # Desactivar interfaz UI de Swagger en prod

server:
  error:
    include-message: never # No filtrar mensajes de excepción internos al cliente
    include-stacktrace: never # Ocultar trazas de pila (Stacktraces)
    include-binding-errors: never

# Validaciones extras recomendadas de logs
logging:
  level:
    root: WARN
    edu.universidad.servicios: INFO
